name: "Push RDMA CNI images on merge to master"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  BUILD_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x

on:
  push:
    branches:
      - master

jobs:
  build-and-push-rdma-cni:
    name: Image push
    runs-on: ubuntu-24.04

    steps:
      - name: check out the repo
        uses: actions/checkout@v6

      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push RDMA CNI multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: ./Dockerfile

